{% set name = "maeparser" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/schrodinger/maeparser/archive/v{{ version }}.tar.gz
  sha256: a8d80f67d1b9be6e23b9651cb747f4a3200132e7d878a285119c86bf44568e36
  patches:
    - patches/001-patch-cmake-config-path.patch
build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
  host:
    - libboost-devel
    - zlib

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - libboost-devel
    - zlib
  files:
    - cmake_test/test.cpp
    - cmake_test/CMakeLists.txt
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist "%LIBRARY_LIB%\\{{ name }}.lib" exit 1  # [win]
    - cd cmake_test
    - cmake .
    - cmake --build .

about:
  home: https://github.com/schrodinger/maeparser
  summary: 'maestro file parser'
  description: |
    maeparser is a parser for Schrodinger Maestro files.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/schrodinger/maeparser

extra:
  recipe-maintainers:
    - SimonBoothroyd
